// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6RxD6b1G1rLYzp2hsExzDQJVkfTPfzO8',
    appId: '1:943040419024:web:de24c97126c2ebf79f7ad5',
    messagingSenderId: '943040419024',
    projectId: 'repuestospro-prod',
    authDomain: 'repuestospro-prod.firebaseapp.com',
    storageBucket: 'repuestospro-prod.firebasestorage.app',
    measurementId: 'G-H8FC54DSWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9lLjoqmsRNviNjVkmLE5fXaKzrXj6EU',
    appId: '1:943040419024:android:780a9366f1f292209f7ad5',
    messagingSenderId: '943040419024',
    projectId: 'repuestospro-prod',
    storageBucket: 'repuestospro-prod.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6RxD6b1G1rLYzp2hsExzDQJVkfTPfzO8',
    appId: '1:943040419024:web:61fdc27ef96a550d9f7ad5',
    messagingSenderId: '943040419024',
    projectId: 'repuestospro-prod',
    authDomain: 'repuestospro-prod.firebaseapp.com',
    storageBucket: 'repuestospro-prod.firebasestorage.app',
    measurementId: 'G-CLVS8GHRTL',
  );
}
